version: '3.1'
services:

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine

  stats-server:
    build: ./stats
    image:
      image_stats
    container_name:
      container_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      container_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
