version: '3.1'
services:

  stats-server:
    build: ./stats
    image:
      image_stats
    container_name:
      container_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      container_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm
    image:
      image_ewm
    container_name:
      container_ewm
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - STATS_URL=http://stats-server:9090
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image:
      postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      container_ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root